eureka:
  client:
    service-url.defaultZone: http://root:root@itoken-eureka1:8761/eureka,http://root:root@itoken-eureka2:8762/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8888

spring:
  application:
    name: itoken-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/JokeSanchez/Itoken.git
          search-paths: itoken-config/respo
          username: JokeSanchez
          password: zmt569957919