eureka:
  client:
    service-url.defaultZone: http://root:root@itoken-eureka1:8761/eureka,http://root:root@itoken-eureka2:8762/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8005

spring:
  application:
    name: itoken-zuul

zuul:
  routes:
    aaa:
      path: /eurekaui/**
      service-id: eurekaui