eureka:
  client:
    service-url.defaultZone: http://root:root@localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8005

spring:
  application:
    name: itoken-zuul

zuul:
  routes:
    aaa:
      path: /eurekaui/**
      service-id: eurekaui